FROM python:3.6

WORKDIR /project

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY src src 

COPY setup.py setup.py


RUN pip install --no-deps .
COPY .compmake.rc .
COPY Makefile Makefile
CMD make tests
